const scores = [85, 90, 78];
const ages = [18, 21, 16, 25];
const words = ["apple", "banana", "cherry", "date"];
const numbers = [1, 2, 3, 4];
const expenses = [50, 100, 150];
let sc = scores.find(sc => sc > 80);
console.log(sc);
let ag = scores.find(ag => ag > 20);
console.log(ag);
let word = words.find(word => word.length > 5);
console.log(word);